### ISSUE TITLE
start working on navbar

### ISSUE THREAD

**Issue by KshitizSharma11** [arjunsolanki2612/EventPrepp#5]
make a dynamic navbar under organims 
for mobile devices make a separate sidebar nav option which opens when user clicks on hamburger icon

**Comment by Duytoan049** [comment]
Hello, I will try my best to help you solve this problem, can you assign this to me? This is my first time working with source code

**Comment by KshitizSharma11** [comment]
> Hello, I will try my best to help you solve this problem, can you assign this to me? This is my first time working with source code

hey there, I will assign this to you. Please write clean and well-structured code according to the atomic file structure. Keep nav items inside a separate file inside the atoms folder and import them inside the navbar component to make code clean. just add about 5 dummy items for now.
make sure the Navbar is dynamic for all devices.

**Comment by KshitizSharma11** [comment]
closed via #9
